--
-- Copyright 2017 Poesys Associates. All rights reserved.
--
-- Generated by AndroMDA Poesys/DB cartridge.
-- Template: SubsystemMySqlSchemaTables.vsl
-- Modified to correct generation issues.

-- SQL schema for account subsystem


CREATE TABLE CapitalEntity (
  capitalEntityName VARCHAR(500) NOT NULL,  
  CONSTRAINT CpE_PK PRIMARY KEY (capitalEntityName)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE FiscalYear (
  year INT(4) NOT NULL,
  CONSTRAINT FsY_PK PRIMARY KEY (year),
  startDate TIMESTAMP NOT NULL DEFAULT NOW(),  
  endDate TIMESTAMP NOT NULL DEFAULT NOW()
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE Entity (
  entityName VARCHAR(500) NOT NULL,
  CONSTRAINT En_PK PRIMARY KEY (entityName)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE Account (
  entityName VARCHAR(500),
  CONSTRAINT AcEn_FK 
    FOREIGN KEY (entityName) REFERENCES Entity(entityName) 
    ON UPDATE CASCADE ON DELETE CASCADE,
  accountName VARCHAR(100) NOT NULL,  
  description VARCHAR(500) NOT NULL,  
  debitDefault BOOLEAN NOT NULL DEFAULT 1,  
  active BOOLEAN NOT NULL DEFAULT 1,  
  CONSTRAINT Ac_PK PRIMARY KEY (accountName, entityName)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE SimpleAccount (
  accountName VARCHAR(100) NOT NULL,  
  entityName VARCHAR(500) NOT NULL,  
  CONSTRAINT SimpleAccountPK PRIMARY KEY (accountName, entityName),
  CONSTRAINT SmA_Ac_FK FOREIGN KEY (accountName, entityName)
    REFERENCES Account (accountName, entityName) ON UPDATE CASCADE ON DELETE CASCADE,
  receivable BOOLEAN NOT NULL DEFAULT 0  
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE CapitalAccount (
  accountName VARCHAR(100) NOT NULL,  
  entityName VARCHAR(500) NOT NULL,  
  CONSTRAINT CpA_PK PRIMARY KEY (accountName, entityName),
  CONSTRAINT CpA_Ac_FK FOREIGN KEY (accountName, entityName)
    REFERENCES Account (accountName, entityName) ON UPDATE CASCADE ON DELETE CASCADE,
  ownership NUMERIC NOT NULL,  
  capitalEntityName VARCHAR(500) NOT NULL,
  CONSTRAINT CpA_CpE_FK FOREIGN KEY (capitalEntityName) 
    REFERENCES CapitalEntity (capitalEntityName) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE DistributionAccount (
  accountName VARCHAR(100) NOT NULL,  
  entityName VARCHAR(500) NOT NULL,  
  CONSTRAINT DsA_PK PRIMARY KEY (accountName, entityName),
  CONSTRAINT DsA_Ac_FK FOREIGN KEY (accountName, entityName)
    REFERENCES Account (accountName, entityName) ON UPDATE CASCADE ON DELETE CASCADE,
  capitalEntityName VARCHAR(500) NOT NULL, 
  CONSTRAINT DsA_CpE_FK FOREIGN KEY (capitalEntityName)
    REFERENCES CapitalEntity (capitalEntityName) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE AccountType (
  accountType VARCHAR(15) NOT NULL,  
  CONSTRAINT AcT_PK PRIMARY KEY (accountType)
) ENGINE=InnoDB CHARSET=utf8;

INSERT INTO AccountType (accountType) VALUES ('Assets');
INSERT INTO AccountType (accountType) VALUES ('Liabilities');
INSERT INTO AccountType (accountType) VALUES ('Equity');
INSERT INTO AccountType (accountType) VALUES ('Income');
INSERT INTO AccountType (accountType) VALUES ('Expenses');

CREATE TABLE AccountGroup (
  accountType VARCHAR(15) NOT NULL,  
  orderNumber INT NOT NULL,  
  groupName VARCHAR(100) NOT NULL,  
  CONSTRAINT AcG_PK PRIMARY KEY (accountType, orderNumber),
  CONSTRAINT AcG_AcT_FK FOREIGN KEY (accountType)
    REFERENCES AccountType (accountType)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE FiscalYearAccount (
  accountName VARCHAR(100) NOT NULL,  
  entityName VARCHAR(500) NOT NULL,  
  year INT(4) NOT NULL,  
  orderNumber INT NOT NULL,  
  accountType VARCHAR(15) NOT NULL,  
  groupOrderNumber INT NOT NULL,  
  CONSTRAINT FsYA_PK PRIMARY KEY (accountName, entityName, year),
  CONSTRAINT FsYA_Ac_FK FOREIGN KEY (accountName, entityName)
    REFERENCES Account (accountName, entityName) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FsYA_FsY_FK FOREIGN KEY (year)
    REFERENCES FiscalYear (year) ON DELETE CASCADE,
  CONSTRAINT FsYA_AcG_FK FOREIGN KEY (accountTypeName, groupOrderNumber) 
    REFERENCES AccountGroup(accountType, orderNumber) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB CHARSET=utf8;
