--
-- Copyright 2016 Poesys Associates. All rights reserved.
--
-- Generated by AndroMDA Poesys/DB cartridge.
-- Template: SubsystemMySqlSchemaTables.vsl

-- SQL schema for account subsystem

CREATE TABLE FiscalYear (
  year INT(4) NOT NULL,
  CONSTRAINT FiscalYearPK PRIMARY KEY (year),
  startDate TIMESTAMP NOT NULL DEFAULT NOW(),  
  endDate TIMESTAMP NOT NULL DEFAULT NOW()
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE Entity (
  entityName VARCHAR(500) NOT NULL,
  CONSTRAINT En_PK PRIMARY KEY (entityName)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE AccountGroup (
  groupName VARCHAR(200) NOT NULL,
  CONSTRAINT AcG_PK PRIMARY KEY (groupName)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE Account (
  entityName VARCHAR(500),
  CONSTRAINT AcEn_FK 
    FOREIGN KEY (entityName) REFERENCES Entity(entityName) 
    ON UPDATE CASCADE ON DELETE CASCADE,
  accountName VARCHAR(100) NOT NULL,  
  description VARCHAR(500) NOT NULL,  
  debitDefault BOOLEAN NOT NULL DEFAULT 1,  
  accountType VARCHAR(100) NOT NULL,  
  receivable BOOLEAN NOT NULL DEFAULT 0,  
  active BOOLEAN NOT NULL DEFAULT 1,  
  groupName VARCHAR(200) NOT NULL,
  CONSTRAINT AcGr_FK FOREIGN KEY (groupName) REFERENCES AccountGroup(groupName) 
    ON UPDATE CASCADE ON DELETE CASCADE,  
  CONSTRAINT Ac_PK PRIMARY KEY (accountName, entityName)
) ENGINE=InnoDB CHARSET=utf8;

ALTER TABLE Account ADD CONSTRAINT AcAcT_CK CHECK (accountType IN ('Asset', 'Liability', 'Equity', 'Income', 'Expense'));

CREATE TABLE FiscalYearAccount (
  accountName VARCHAR(100) NOT NULL,  
  entityName VARCHAR(500) NOT NULL,  
  year INT(4) NOT NULL,  
  orderNumber INT,  
  CONSTRAINT FsYA_PK PRIMARY KEY (accountName, entityName, year),
  CONSTRAINT FsYA_Ac_FK FOREIGN KEY (accountName, entityName)
    REFERENCES Account (accountName, entityName) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FsYA_FsY_FK FOREIGN KEY (year)
    REFERENCES FiscalYear (year) ON DELETE CASCADE
) ENGINE=InnoDB CHARSET=utf8;
