--
-- Copyright 2017 Poesys Associates. All rights reserved.
--
-- Generated by AndroMDA Poesys/DB cartridge: DO NOT EDIT DIRECTLY.
-- Template: SubsystemMySqlSchemaTables.vsl

-- Drop all database tables. Order is important.

DROP TABLE IdMap;
DROP TABLE Sequence;

DROP TABLE Reimbursement;
DROP TABLE Item;
DROP TABLE Transaction;

DROP TABLE CapitalAccount;
DROP TABLE DistributionAccount;
DROP TABLE SimpleAccount;
DROP TABLE CapitalEntity;
DROP TABLE FiscalYearAccount;
DROP TABLE Account;
DROP TABLE AccountGroup;
DROP TABLE AccountType;
DROP TABLE Entity;
DROP TABLE FiscalYear;
